### PR TITLE
hide the google translate button

### PR DESCRIPTION
**Pull request by MStruller**

### CODE REVIEW

**Comment by klas** [comment]
I was thinking to do the same - or - as it is now - keep a button and give an error if there is no key. Advantage of the second approach is that we kinda notify people that this feature exists, but I guess it can become distracting for those not using it

**Comment by MStruller** [comment]
for the second i think there must add  in the joomfish conig under the GoogleApiKey an hideButton option for user there not want the GoogleApi. I am not a friend from automatic translation, i use only tranlstors to get an overview for things i can not understand.

**Comment by akempkens** [comment]
a) can it be that you created two pull request with the same "SQL unpublished make error" fix?
b) I'm unsure about "hiding" the G-Translate solution. Many people ask us about it and so far we have not had complains that it exists.

**Comment by akempkens** [comment]
Ok figured out that you fixed these things in a different branch. I separated it and integrated the SQL topic. The Google API I kept as it is.

**Comment by MStruller** [comment]
I thinking why not make in the config ( where the user must set the GoogleApiKey ) we make also an hide Option
as standard 'not hide', so the user know about G-Translate but can hide if not want to use,
i am know the button, but i want allways click it (damned) klas write :but I guess it can become distracting for those not using it.

The SQL topic is not merged.

**Comment by akempkens** [comment]
I double checked the SQL topic and it is included in the downloadable package for the tag. It is also included in my head version of the master.

**Comment by MStruller** [comment]
i also check it again dificult results
on Code->Files the zip has not changed also the code in jf-core / admin / models / cpanel.php
on Code->Tag the zip is changed

**Comment by akempkens** [comment]
I pushed everything upstream again - seems I missed that today morning. Sorry

**Pull request closed without merging**
